apiVersion: apps/v1

kind: Deployment
metadata:
  name: whale-deployment
  labels:
    app: whaleLabel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whaleLabel
  template:
    metadata:
      labels:
        app: whaleLabel
    spec:
      containers:
        - name: whale-example
          image: whale-example:1.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: whale-service
spec:
  type: NodePort
  selector:
    app: whaleLabel
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003
