apiVersion: apps/v1

kind: Deployment
metadata:
  name: container-deployment
  labels:
    app: containerLabel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerLabel
  template:
    metadata:
      labels:
        app: containerLabel
    spec:
      containers:
        - name: container-example
          image: container-example:1.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: container-service
spec:
  type: NodePort
  selector:
    app: containerLabel
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
