apiVersion: apps/v1

kind: Deployment
metadata:
  name: ocean-deployment
  labels:
    app: oceanLabel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oceanLabel
  template:
    metadata:
      labels:
        app: oceanLabel
    spec:
      containers:
        - name: ocean-example
          image: ocean-example:1.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ocean-service
spec:
  type: NodePort
  selector:
    app: oceanLabel
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
