version: '3.8'

services:
  container-example:
    image: container-example:1.0
    build:
      context: ./ContainerExample
      dockerfile: Dockerfile
    ports:
      - 8081:8080

  ocean-example:
    image: ocean-example:1.0
    build:
      context: ./OceanExample
      dockerfile: Dockerfile
    ports:
      - 8082:8080

  whale-example:
    image: whale-example:1.0
    build:
      context: ./WhaleExample
      dockerfile: Dockerfile
    ports:
      - 8083:8080
